build: add workflow for building and testing on GitHub Actions

diff --git a/src/tests/modeltests b/src/tests/modeltests
--- a/src/tests/modeltests
+++ b/src/tests/modeltests
@@ -1,22 +1,37 @@
-#!/usr/bin/env sh
-# Use the global sde command if it is available.
+#!/bin/bash
+
+set -e # fail on error
+
+# Use the local sde command.
 SDE='node ../sde.js'
-if which sde >/dev/null; then SDE=sde; fi
 $SDE -v &>/dev/null
 if [[ $? -ne 0 ]]; then
   echo 'SDEverywhere is not installed.'
-  echo 'Run "npm install" in the src directory to install it locally.'
-  echo 'You could also install it globally with "npm install sdeverywhere -g".'
+  echo 'Run "npm install" in the top directory to install it locally.'
   exit 1
 fi
-# Test each model against saved Vensim data.
-for MODEL in $(ls ../../models); do
-  echo "testing the $MODEL model"
-  $SDE clean --modeldir ../../models/$MODEL
-  CMD="$SDE test ../../models/$MODEL/$MODEL -p 1e-4"
-  if [[ $MODEL == 'directdata' ]]; then
-    CMD="$CMD --spec ../../models/$MODEL/spec.json"
+
+function test {
+  MODEL=$1
+  echo "Testing the $MODEL model"
+  MODEL_DIR=../../models/$MODEL
+  $SDE clean --modeldir $MODEL_DIR
+  if [[ -f $MODEL_DIR/spec.json ]]; then
+    TEST_ARGS="--spec $MODEL_DIR/spec.json"
+  else
+    TEST_ARGS=
   fi
-  $CMD
-  $SDE clean --modeldir ../../models/$MODEL
-done
+  $SDE test $TEST_ARGS -p 1e-4 $MODEL_DIR/$MODEL
+  $SDE clean --modeldir $MODEL_DIR
+  echo
+}
+
+if [[ -n $1 ]]; then
+  # Test the given model against saved Vensim data.
+  test $1
+else
+  # Test each model against saved Vensim data.
+  for m in $(ls ../../models); do
+    test $m
+  done
+fi
